### ISSUE TITLE
Request uploading Resources folder to repo

### ISSUE THREAD

**Issue by oLMHo** [goto-bus-stop/recanalyst#3]
A lot of functions require referencing images in Resources folder which could not been found in this repo, I have looked into the biegleux latest version in Sourceforge and found some old resources. However, that project is only designed for AOC not AoFE, some of the images are missing. Could you also put the Resources folder you used for testing to the repo so that we could use it without regenerating the images for AoFE?

**Comment by goto-bus-stop** [comment]
Oh, that's a good point. Officially I can't put them up in the repo because of copyright issues, but I can upload them elsewhere and add a link or something. I'll get back to you once I've done that :)

**Comment by oLMHo** [comment]
Thanks!

**Comment by goto-bus-stop** [comment]
@oLMHo These resources are currently used on the ZeroEmpires forums: http://idlebeaver.ninja/recanalyst/resources.tar.gz

That includes (most?) AoFE civs and researches as well.

**Comment by oLMHo** [comment]
Great!
