### ISSUE TITLE
HD Edition: Rise of the Rajas

### ISSUE THREAD

**Issue by goto-bus-stop** [goto-bus-stop/recanalyst#40]
Likely not many changes in the format from 4.8 (#27). However will need to make sure that the Openage convert script can handle the new terrains etc., and add the resources here.

Version info:

Patch version: 5.0
Version string: VER 9.4
Subversion number: 12.50

**Comment by coffenbacher** [comment]
Looking forward to seeing some of the parsed recs, especially of the Nicov games !

**Comment by goto-bus-stop** [comment]
Let's hope so, I've not been able to parse patch 4.8 recs so far :laughing:
