### ISSUE TITLE
API doc is missing?

### ISSUE THREAD

**Issue by lichifeng** [goto-bus-stop/recanalyst#49]
Thanks for your awesome work.

But the link to API doc in Readme.md seems broken?

Is there a new place for API documentation?

Thanks again.

**Comment by lichifeng** [comment]
http://rene.kooi.me/recanalyst/doc/v4.1.2/

I found the correct link

**Comment by goto-bus-stop** [comment]
I'll fix the readme link for the next release. Thanks for letting me know!
