### ISSUE TITLE
Resources DLL File?

### ISSUE THREAD

**Issue by gregstein** [goto-bus-stop/recanalyst#70]
Hello,
I hope you are doing well!

I wanted to ask whether there is a .dll file containing all resources of #https://github.com/goto-bus-stop/recanalyst/blob/f1f9bf8d92cb9e998de3e9b5e73cde32bab03b1c/resources/lang/en/ageofempires.php ?

Thank you!

**Comment by goto-bus-stop** [comment]
the language strings in this repository are taken from the HD edition strings files using this script: https://github.com/goto-bus-stop/recanalyst/blob/master/tools/makeResources.php

in AoC 1.0c, they are spread out across the three language*.dll files

**Comment by gregstein** [comment]
I don't want to extract them. I meant the icons of those resources stored in a .dll file to retrieve externally.

**Comment by goto-bus-stop** [comment]
i don't follow. there is no DLL file with icons. HD edition has SLP files for icons in the resources folder. AoC has them in its interfac.drs archive file. this repository actually doesn't do anything with dlls at all

**Comment by gregstein** [comment]
lol that's unfortunate, because I have managed to port [aoc-mgz](https://github.com/happyleavesaoc/aoc-mgz/) to C#/IronPython. So I guess i have to build my own dll library to include all icons in one file for easy calls throughout the code. It's going to be a desktop RecAnalyst.

**Comment by gregstein** [comment]
Thank you for your time <3 as usual
